---
- name: "Git clone ReadyToTouch"
  hosts: "web"
  gather_facts: "no"
  vars:
    - REPOSITORY: "https://github.com/readytotouch/readytotouch.git"
    - DESTINATION: "/var/go/readytotouch"

  tasks:
    - name: "Ensure directory {{ DESTINATION }} exists"
      ansible.builtin.file:
        path: "{{ DESTINATION }}"
        state: "directory"

    - name: "Git pull repository {{ REPOSITORY }}"
      ansible.builtin.git:
        repo: "{{ REPOSITORY }}"
        version: "main"
        dest: "{{ DESTINATION }}"
