- absl-py==1.4.0
- albumentations==1.0.0
- anyio==4.4.0
- astor==0.8.1
- cachetools==5.3.0
- certifi==2024.2.2
- charset-normalizer==2.1.1
- contourpy==1.2.1
- cycler==0.12.1
- Cython==3.0.10
- decorator==5.1.1
- dlib==19.24.4
- docopt==0.6.2
- dominate==2.9.1
- easydict==1.10
- exceptiongroup==1.2.1
- facenet-pytorch==2.6.0
- ffmpeg==1.4
- filelock==3.13.4
- flatbuffers==24.3.25
- fonttools==4.51.0
- fsspec==2024.3.1
- google-auth==2.16.2
- google-auth-oauthlib==0.4.6
- grpcio==1.51.3
- h11==0.14.0
- httpcore==1.0.5
- httpx==0.27.0
- huggingface-hub==0.22.2
- idna==3.4
- imageio==2.26.0
- importlib-metadata==6.0.0
- importlib_resources==6.4.0
- imutils==0.5.4
- insightface==0.7.3
- Jinja2==3.1.3
- joblib==1.4.0
- kiwisolver==1.4.5
- kornia==0.6.8
- lightning-utilities==0.11.2
- lpips==0.1.4
- Markdown==3.4.1
- MarkupSafe==2.1.2
- matplotlib==3.7.4
- mpmath==1.3.0
- munch==4.0.0
- natsort==8.4.0
- networkx==3.0
- ninja==1.10.2
- numpy==1.26.4
- nvidia-cublas-cu12==12.1.3.1
- nvidia-cuda-cupti-cu12==12.1.105
- nvidia-cuda-nvrtc-cu12==12.1.105
- nvidia-cuda-runtime-cu12==12.1.105
- nvidia-cudnn-cu12==8.9.2.26
- nvidia-cufft-cu12==11.0.2.54
- nvidia-curand-cu12==10.3.2.106
- nvidia-cusolver-cu12==11.4.5.107
- nvidia-cusparse-cu12==12.1.0.106
- nvidia-nccl-cu12==2.19.3
- nvidia-nvjitlink-cu12==12.4.127
- nvidia-nvtx-cu12==12.1.105
- oauthlib==3.2.2
- onnx==1.16.1
- onnxruntime==1.8.0
- opencv-python==4.6.0.66
- opencv-python-headless==4.9.0.80
- opt-einsum==3.3.0
- packaging==23.0
- paddlepaddle==2.6.1
- pandas==1.4.4
- pillow==10.2.0
- pipreqs==0.4.13
- prettytable==3.10.0
- protobuf==3.20.0
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pyparsing==3.1.2
- python-dateutil==2.9.0.post0
- pytz==2024.1
- PyWavelets==1.4.1
- PyYAML==6.0
- requests==2.28.1
- requests-oauthlib==1.3.1
- retinaface-pytorch==0.0.8
- rsa==4.9
- safetensors==0.4.3
- scikit-image==0.19.3
- scikit-learn==1.3.2
- scipy==1.10.1
- six==1.16.0
- sniffio==1.3.1
- sympy==1.12
- tensorboard==2.8.0
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.1
- tensorboardX==2.6.2.2
- threadpoolctl==3.4.0
- tifffile==2023.2.28
- timm==0.9.12
- torch==1.9.0+cu111
- torchaudio==0.9.0
- torchmetrics==1.2.0
- torchvision==0.10.0+cu111
- tqdm==4.64.1
- triton==2.2.0
- typing_extensions==4.11.0
- urllib3==1.26.14
- wcwidth==0.2.13
- Werkzeug==2.2.3
- yarg==0.1.9
- zipp==3.15.0
